name: Eventy

packages:
  - packages/**

scripts:
  # Only run this command in packages and libraries that depends on Flutter SDK 
  # This will exclude running in database library since it is pure dart
  # and does not depend on Flutter SDK.
  postbootstrap: melos exec --flutter -- flutter pub get
  codegen: melos exec --no-flutter -- dart pub run build_runner build --delete-conflicting-outputs
  test_flutter: melos exec --flutter -- flutter test
  test_dart: melos exec --no-flutter -- dart test
  