name: Eventy
repository: https://github.com/Cloverspace/Eventy/

packages:
  - packages/**

scripts: 
  analyze: melos exec -- "dart analyze ."
  postbootstrap: melos exec -- "flutter pub get"
  codegen: melos exec --scope="*database*" -- "flutter pub run build_runner build --delete-conflicting-outputs"