# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
          scalars:
            uuid:
              type: String
            timestamp:
              type: DateTime
            json:
              type: Map<String, dynamic>