name: database
description: Database library for Eventy
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies: 
  graphql_flutter: ^5.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.10
  json_serializable: ^6.1.6
  coverage: ^1.1.0
  graphql_codegen: ^0.7.2
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
