name: eventy_organizer
description: Eventy application for hosting or organizing events
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  database:
    path: ../database
  date_time_picker: ^2.1.0
  equatable: ^2.0.3
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  geocoding: ^2.0.4
  geolocator: ^8.2.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  local_storage_api:
    path: ../local_storage_api
  modal_bottom_sheet: ^2.0.1
  persistent_bottom_nav_bar_v2: ^4.1.11

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/