name: eventy_organizer
description: Eventy application for hosting or organizing events
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  database:
    path: ../database
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  gap: ^2.0.0
  intl: ^0.17.0
  local_storage_api:
    path: ../local_storage_api
  modal_bottom_sheet: ^2.0.1
  persistent_bottom_nav_bar: ^4.0.2

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
