name: consumer
description: Eventy application for Consumers
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  common:
    path: ../common/
  database:
    path: ../database/
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf
          weight: 700
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        - asset: assets/fonts/AirbnbCereal_W_lt.otf
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
          weight: 500
        - asset: assets/fonts/AirbnbCereal_W_XBd.otf
          weight: 900
          
  uses-material-design: true
  generate: true
